application: diet-futar
version: 13
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /styles
  static_dir: styles
- url: .*
  script: switch.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest