application: diet-futar
version: 45-weekly-sheet
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: css
- url: /font
  static_dir: font
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /static
  static_dir: static
- url: .*
  script: switch.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest